version: '3.5'

services:

    educapi:
        container_name: educapi
        image: a4sufpb/educapi:latest
        restart: always
        ports:
            - "8080:8080"
        networks:
            - educapi-network
        depends_on:
            - db
        env_file:
            - ./prod.env
    db:
        container_name: postgres-educapi
        image: postgres:12.3
        restart: always
        ports:
            - "5444:5432"
        networks:
            - educapi-network
        volumes:
            - educapi:/var/lib/postgresql/data
        env_file:
            - ./prod.env

volumes:
    educapi: {}

networks:
    educapi-network:
        driver: bridge
