version: '3.5'

services:

    educapi:
        container_name: educapi
        image: a4sufpb/educapi:1.0.7
        restart: always
        ports:
            - "8080:8080"
        networks:
            - educapi-network
        depends_on:
            - db
        env_file:
            - .env
    db:
        container_name: postgres-educapi
        image: postgres:12.3
        restart: always
        networks:
            - educapi-network
        volumes:
            - educapi:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata

volumes:
    educapi:

networks:
    educapi-network:
        driver: bridge