version: '3.5'

services:

    educapi:
        container_name: educapi
        build:
            context: .
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        container_name: postgres-educapi
        image: postgres:12.3
        restart: always
        volumes:
            - postgres-educapi:/data/postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: educapi
            PGDATA: /data/postgres


volumes:
    postgres-educapi:
