spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:file:./data
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true