spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        url: ${DB_URL}
        username: ${POSTGRES_USER}
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true