name: Build Docker Image And Push Docker Hub

on:
  push:
    branches: [master]

jobs:

  build-and-push:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USER}}/educapi .

      - name: Push Image to Docker Hub
        run: docker push ${{secrets.DOCKER_USER}}/educapi

#      - name: Connecting and Deploying to the SSH Server
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_SECRET_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            cd EducAPI
#            docker rm -f educapi
#            docker pull a4sufpb/educapi
#            docker compose up -d