# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Development workflow 

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Spring Boot project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run:  mvn package -DskipTests

      - name: Run unit tests
        run: mvn test